public with sharing class AccountTriggerHandler extends TriggerHandler {
   // public override void beforeUpdate() {
      //  AccountHelper.verifyCNPJ(Trigger.new );
       // AccountHelper.verifyCPF(Trigger.new);
   // }

   // public override void beforeInsert() {
     //   AccountHelper.verifyCPF(Trigger.new);
   // }

    //public override void afterUpdate() {
       // AccountHelper.verifyCPF(Trigger.new );
   // }

   // public override void afterInsert() {
     //   AccountHelper.verifyCPF(Trigger.new);
   // }
}