public class RoletaLeadsTriggerHandler extends TriggerHandler {
    public override void afterInsert() {
      
        // RoletaLeadsHelper.LeadsBolsao(Trigger.new);
        
        // LeadsBolsaoScheduler.scheduleDailyJobs();
    }

    public override void afterUpdate() {
        
        // RoletaLeadsHelper.LeadsBolsao(Trigger.new);
        
        // LeadsBolsaoScheduler.scheduleDailyJobs();
    }
}