name: Deploy das alterações para UAT
on:
  pull_request:
    types: [closed]
    branches:
      - qa
    paths:
      - 'force-app/**'
      - 'manifest/package.xml' 

jobs:
  deploy_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Autenticar no Salesforce
        run: echo ${{ secrets.AUTH_URL_UAT }} > sfdx-auth-url.txt

      - name: Conectar ao Salesforce
        run: sf org login sfdx-url -f sfdx-auth-url.txt --alias uat

      - name: Executar Deploy na HML
        run: sf project deploy start --test-level NoTestRun -x manifest/package.xml -o uat

  close_job:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PR #${{ github.event.number }} foi fechado sem realizar o merge."
